name: Conclusion

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Heart-Welcome Message
        run: |
          echo "ğŸ‘‹ Hello, ${{ github.actor }}! ğŸ‘‹"
          echo "â¤ï¸ Welcome to the project! Have a great day! ğŸ˜Š"
